name: hows_the_weather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  geolocator: ^13.0.2
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
